Blog/ViewComponents/ListaCategoriasViewComponent.cs
using Blog.DAO;
using Microsoft.AspNetCore.Mvc;

namespace Blog.ViewComponents
{
    public class ListaCategoriasViewComponent : ViewComponent
    {
        private readonly PostDAO _dao;

        public ListaCategoriasViewComponent(PostDAO dao)
        {
            _dao = dao;
        }

        public IViewComponentResult Invoke()
        {
            var posts = _dao.ListaPublicados();
            var categoriaQuantidade = new Models.CategoriaComQuantidadeViewModel(posts);

            return View(categoriaQuantidade);
        }
    }
}

Blog/Views/Shared/Cabecalho.cshtml
<header>
    <div class="jumbotron">
        <h1>Resenha Cultural</h1>
        <p>Críticas bem humoradas sobre filmes, musicas, livros e tudo o que agita o cenario cultural.</p>
    </div>
</header>

Blog/Views/Shared/Lateral.cshtml
<aside>
    <div>
        @using (Html.BeginForm("BuscaPeloTermo", "Home", FormMethod.Get, new { @class = "inline-form" }))
        {
            <div class="input-group">
                @Html.TextBox("termo", null, new { @class = "form-control", @plarceholder = "Buscar por..." })
                <span class="input-group-append">
                    <button class="btn btn-primary" type="submit">Ok</button>
                </span>
            </div>
        }

    </div>
    <div id="categorias">
        @await  Component.InvokeAsync("ListaCategorias")
    </div>
    <div id="autores">
        <h3>Autores</h3>
    </div>
</aside>

Blog/Views/Shared/Rodape.cshtml
<footer>
    <p>&copy; Resenha Cultural - 2019</p>
</footer>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Resenha Cultural</title>
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/estilo.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("Cabecalho")
    <div class="container clearfix">
    <main>
        @RenderBody()
    </main>
    @Html.Partial("Lateral")
    </div>
    @Html.Partial("Rodape")
    @RenderSection("Scripts", false)
</body>
</html>